backend/deploy/deploy.bash
backend/deploy/moonstream.service
crawlers/.gitignore
crawlers/sample.env
db/alembic.sh
db/alembic/env.py

Some small fixes and improvements.
Locally.

Small fixes in moonstreamdb module

---

backend/deploy/deploy.bash
backend/deploy/moonstream.service
backend/requirements.txt

Fixes to working backend deployment

---

crawlers/moonstreamcrawlers/cli.py
crawlers/moonstreamcrawlers/ethereum.py
db/.gitignore

Sync blocks crawlers

---

crawlers/moonstreamcrawlers/cli.py

Small fix for CLI crawler sync command

---

backend/requirements.txt

Updated git commit for db at backend part

---

crawlers/moonstreamcrawlers/cli.py
crawlers/moonstreamcrawlers/ethereum.py

Now missing blocks check finishing in seconds.

Improved speed for missing blocks command check

---

frontend/pages/index.js
frontend/src/components/EntriesNavigation.js

Stop button

---

frontend/src/components/Footer.js
frontend/src/components/LandingNavbar.js
frontend/src/components/Scrollable.js
frontend/src/components/SignIn.js

Small changes to landing page : names, links, spacings
partially resolves #1

Landing improvements

---

frontend/pages/_document.js

google analytics

---

backend/moonstream/cli.py
backend/requirements.txt
backend/setup.py

Updated backend CLI to create subscription types.
Tested by creating `ethereum_blockchain` subscription on production. :)

Fix moonstream cli

---

frontend/src/core/services/subscriptions.service.js

Add slash ficing.

---

frontend/src/components/StreamEntry.js
frontend/src/components/TxInfo.js
frontend/src/core/hooks/index.js
frontend/src/core/hooks/useTxCache.js
frontend/src/core/hooks/useTxInfo.js

Prettier formatting

---

frontend/src/components/NewSubscription.js

Fixing issue with subscription_plan_is.

quick fix.

---

frontend/pages/index.js

Will test it on main and revert if it does not fix anything
#60

Experiment to fix redirect issue 

---

frontend/pages/_app.js

Try to fix redirects

---

frontend/pages/_app.js

copy _app from bugout dev

---

frontend/pages/_app.js
frontend/styles/nprogress.css

fix imports

---

frontend/pages/_app.js

fix query cache props

---

frontend/pages/index.js

remove UI context dynamic loading

---

frontend/src/components/NewSubscription.js

new subscriptions error messaage names  fix

---

backend/moonstream/data.py
backend/moonstream/routes/subscriptions.py
frontend/src/core/services/subscriptions.service.js

Add endpoint for update subscription.
https://github.com/bugout-dev/moonstream/issues/62

Add update subscription.

---

backend/requirements.txt
backend/setup.py

This allows us to udpate resources (needed for subscription edits).
Fixes a bug where I merged @Andrei-Dolgolev 's previous pull request before we had published Bugout to PyPI.
Manually
Resolves https://github.com/bugout-dev/moonstream/issues/62

Bumped bugout-python dependency to 0.1.16

---

README.md

Made the README more informative.

Improved main README for the repo

---

backend/moonstream/actions.py
backend/moonstream/routes/streams.py
frontend/src/components/EntriesNavigation.js
frontend/src/components/SubscriptionsList.js
frontend/src/core/hooks/useStream.js
frontend/src/core/services/stream.service.js

1) issue with empty value in filter
2) issue with empty ethereum transaction query
Add
1) Add urlencoding and replace null to 0 for timestamps
2) Add sorting by timestamps

Fix issues.

---

frontend/src/core/providers/UIProvider/index.js
frontend/src/core/services/stream.service.js

Axios was encoding query parameters and we were doing so as well. Fixed it so that we rely on Axios behaviour.

Fixed issues with stream requests to backend

---

frontend/pages/account/security.js
frontend/pages/analytics.js
frontend/pages/stream/index.js
frontend/pages/subscriptions.js
frontend/src/components/AppNavbar.js
frontend/src/components/EntriesNavigation.js
frontend/src/components/SteamEntryDetails.js
frontend/src/components/StreamEntry.js
frontend/src/components/TxInfo.js
frontend/src/core/hooks/useStream.js
frontend/src/core/hooks/useTxInfo.js
frontend/src/core/providers/UIProvider/index.js
frontend/src/layouts/EntriesLayout.js
frontend/styles/styles.css

Adds `document.title` to 
```
/account/security
/stream
/analytics
```
I merged PR #99 in to this  to avoid merge conflicts
tested locally  on `chrome`
resolves #91 
Merge after #99

document titles

---

frontend/pages/register/index.js

added `/register` path to the website
Tested in localhost with production enviroment
resolves #77

Register page

---

.github/workflows/lint.backend.yml
.github/workflows/lint.crawlers.yml
.github/workflows/lint.db.yml
.github/workflows/lint.frontend.yml

Fixed actions to work only with new PR to main

---

backend/moonstream/actions.py
backend/moonstream/data.py
backend/moonstream/routes/txinfo.py
crawlers/mooncrawl/identity.py
crawlers/sample.env

Fixed errors to work with new labels.
Tested ad dev server.

Fixed parser to work with labels properly to get coinmarketcap

---

frontend/src/components/SteamEntryDetails.js
frontend/src/components/TxInfo.js

Made table smaller, hash title smaller, added `word-break: all` to table rows so long rows like addresses wrap on smaller screens

 entry details will better fit in to split view

---

frontend/pages/_app.js
frontend/pages/stream/index.js
frontend/pages/subscriptions.js
frontend/pages/welcome.js
frontend/src/Theme/Spinner/index.js
frontend/src/Theme/Tooltip/index.js
frontend/src/Theme/theme.js
frontend/src/components/AppNavbar.js
frontend/src/components/EntriesNavigation.js
frontend/src/components/LandingNavbar.js
frontend/src/components/NewModalSubscripton.js
frontend/src/components/NewSubscription.js
frontend/src/components/RouteButton.js
frontend/src/components/Sidebar.js
frontend/src/components/StepProgress.js
frontend/src/components/StreamEntry.js
frontend/src/components/SubscriptionsList.js
frontend/src/components/TxInfo.js
frontend/src/core/hooks/useSignUp.js
frontend/src/core/providers/AnalyticsProvider/constants.js
frontend/src/core/providers/UIProvider/index.js

- Added /welcome page with onboarding flow. It consists of three steps: 
-- Welcome   
-- Setting up subscriptions
-- Working with stream entries
- Added in local storage object that corresponds to onboarding state
- Added section in UI provider that takes care about onboarding state 
- minor code clean ups
- Added redirect from login/signup `onsuccess` in to /welcome page if in UI provider `isOnboardingComplete = false`
- `isOnboardingComplete` is being set to true once user clicks `Finish` on last screen of /welcome page
Localhost, `safari`, `chrome`, `firefox`
resolves https://github.com/bugout-dev/moonstream/issues/78

Signup onboarding flow

---

frontend/src/components/StreamEntry.js
frontend/src/components/stream-cards/EthereumMempool.js

/components: split `StreamEntry.js` in to `StreamEntry.js` and `stream-cards/EthereumMempool.js.
We can use same wrapper of `StreamEntry.js` and define new cards in `components/stream-cards`
resolves #134

split stream card to ethereum card and wrapper

---

backend/moonstream/actions.py
backend/moonstream/data.py
backend/moonstream/routes/txinfo.py
backend/moonstream/settings.py
frontend/src/components/ContractSource.js
frontend/src/components/StreamEntry.js
frontend/src/components/TxInfo.js

Now txInfo component displays smart contract source information if it exists. 
Ressolves #127

Smartcontract source info

---

frontend/pages/welcome.js
frontend/src/components/NewModalSubscripton.js
frontend/src/components/NewSubscription.js

Onboarding content improvement

---

frontend/src/components/Footer.js

added links:
- `/product` 
- `/team`
-  `blog`
- `stay in touch` -> `all the crypto data you care about`
resolves #141

Footer: added about, product, blog, text change

---

frontend/pages/product/index.js

- changed product page content
- changed background image to product page image
- optimized paddings at various screen sizes 
resolves #142

Product page: content and background image

---

frontend/pages/team/index.js

- Added team illustration for first section
- Fixed some weird paddings on large screen view
resolves #151

Team page: team illustration, paddings

---

frontend/src/components/CopyButton.js
frontend/src/core/hooks/useForgotPassword.js
frontend/src/core/hooks/useLogout.js

- IN copy button change `setInterval` to `setTimeout`
- Migrate useMutation in useForgotPassword.js from react-query v2 to v3
- Remove `useEffect` from 'useLogout.js` and move corresponding code in to `onSuccess`
resolves #163

Try fix client side exception

---

frontend/pages/team/index.js

Team page: add marketing list spacing and uncap

---

frontend/src/components/StreamEntry.js

Due to changes in stream entry schema component was broken

onboarding stream sceen StreamEntry card props

---

frontend/pages/welcome.js

Fixing welcome page

---

frontend/src/components/ContractSource.js
frontend/src/components/NewModalSubscripton.js
frontend/src/components/NewSubscription.js
frontend/src/components/StreamEntry.js
frontend/src/components/TxInfo.js
frontend/src/components/stream-cards/EthereumWhalewatch.js

- reworked whale watch card in to simple grid components
- added subscribe to address button if whale watch address is not subscribed yet
- Added initial properties to newSubscription modal that allow to predefine address and type
- Fixes bug with not being able to create new subscription from welcome screen
- Disabled entry details button for whale watch card as it has no details feature right now
- Changed time format to `<Date> from <time> to <time>` if new time date is different format will show as  `<Date> from <time> to <Date> <time>` 
resolves #175

Whale watch card improvement

---

frontend/pages/welcome.js

Subscriptions created from onboaring view are treated not as free subscriptions anymore 

Allow any subscription type to be created from welcome screen 

---

frontend/pages/product/index.js

Product page text alignment

---

crawlers/mooncrawl/mooncrawl/identity.py
crawlers/mooncrawl/sample.env

CMC parser checks address and label exists
Tested and crawled already.

CMC parser checks address and label exists

---

backend/moonstream/actions.py
backend/moonstream/data.py
backend/moonstream/routes/address_info.py
backend/moonstream/routes/txinfo.py

Changed `address_info/` response schema
manually
Resolves #194

fixed address_info response schema

---

crawlers/ethtxpool/main.go

Txpool `value:<eth>` tag.
Tested conversion.

Added value to tags in ether

---

crawlers/mooncrawl/mooncrawl/etherscan.py

Updates https://github.com/bugout-dev/moonstream/pull/238 so that it doesn't include the "import" changes
However https://github.com/bugout-dev/moonstream/pull/238 was tested

(Updated) Etherscan crawler fix

---

db/deploy/deploy.bash
db/deploy/moonstreamdb.service
db/server/go.mod
db/server/main.go

Server returns `status: ok` for `/ping` request.
Tested localy.

Simple ping moonstream database service

---

db/deploy/deploy.bash

Build server Go script on machine

---

db/deploy/moonstreamdb.service

Fixed executable path of moonstreamdb server

---

db/deploy/deploy.bash

Added set eu for deploy

---

backend/moonstream/data.py
backend/moonstream/routes/subscriptions.py

Add created_at and updated_at.

---

frontend/src/components/LandingNavbar.js
frontend/src/components/Navbar.js
frontend/src/components/Sidebar.js
frontend/src/components/SignIn.js
frontend/src/layouts/RootLayout.js

1000k user banner 
Resolves https://github.com/bugout-dev/moonstream/issues/258

1k user banner

---

frontend/src/layouts/RootLayout.js

don't render banner at app view

dont show banner in app view

---

frontend/src/components/LandingNavbar.js
frontend/src/components/Modal/index.js
frontend/src/components/Modal/styles.js
frontend/src/components/stream-cards/EthereumWhalewatch.js
frontend/src/core/hooks/useLogin.js
frontend/src/core/hooks/useLogout.js
frontend/src/core/hooks/useSignUp.js
frontend/src/core/providers/UIProvider/index.js
frontend/src/layouts/AppLayout.js
frontend/src/layouts/RootLayout.js

moved AppView control in AppLayout.js
Added UI state monitors for isLoggingOut, isLoggingIn
Improved AppIsReady and sign up / login logic
Fixed that error

improve login/signup/logout and appLoading view

---

backend/moonstream/providers/bugout.py
backend/moonstream/providers/ethereum_blockchain.py
backend/moonstream/routes/streams.py

This gives information about available event providers on the API. It is a public endpoint and does not require authentication.
Run the API and:
```bash
curl localhost:7481/streams/info | jq .
```

Added /streams/info endpoint

---

crawlers/deploy/deploy.bash

Small fix of path in deplyment script for crawlers

Fixed path in deploy for crawlers

---

crawlers/deploy/ethereum-synchronize.service
crawlers/mooncrawl/mooncrawl/ethcrawler.py

Fixed missing params and added logger for sync crawler

---

backend/moonstream/routes/users.py
frontend/pages/account/tokens.js
frontend/src/components/AccountIconButton.js
frontend/src/components/Sidebar.js
frontend/src/components/TokensList.js
frontend/src/core/hooks/useTokens.js

- Improved table layout for mobile view
- renamed notes to labels 
- made color separation of placeholder of unnamed token id labels to labels
- fixed bug on backend API that caused to add label to token that was passed in authorisation header, not one in the form
- fixed logic to hide frontend token from the table
localhost, local dev server

Token screen

---

docs/architecture.md

Describes Moonstream architecture as a high level.
Introduces a top-level `docs/` directory in which we will put our developer documentation.
n/a

Moonstream architecture documentation

---

crawlers/mooncrawl/mooncrawl/ethcrawler.py
crawlers/mooncrawl/mooncrawl/ethereum.py
crawlers/mooncrawl/mooncrawl/version.py
crawlers/mooncrawl/setup.py

While we have a troubles with Pool execution calls with psycopg2, using Threads executor instead.
Links:
- https://docs.sqlalchemy.org/en/14/core/pooling.html#sqlalchemy.pool.AssertionPool
- https://stackoverflow.com/questions/39493785/sqlalchemy-threadpoolexecutor-too-many-clients
- https://stackoverflow.com/questions/68609796/sqlalchemy-exc-operationalerror-psycopg2-operationalerror-ssl-error-wrong-ve
- https://medium.com/@philamersune/fixing-ssl-error-decryption-failed-or-bad-record-mac-d668e71a5409
localy

Threads instead of pools, missing block cmd check num of transactions

---

crawlers/mooncrawl/mooncrawl/nft/ethereum.py
crawlers/mooncrawl/mooncrawl/reporter.py

Fixed nft crawler, it was not saving labels if there was problem with one contract name/symbol (unicode escape etc.)
added reports with batch information to fix problems later

added reporter to nft crawler, removed global cache for addresses

---

backend/moonstream/actions.py
backend/moonstream/data.py
backend/moonstream/routes/address_info.py

Added support of `erc721` labels which are added in #226
manually

Erc721 labels

---

frontend/src/layouts/RootLayout.js

discord link from aws

---

.github/workflows/release.clients.python.yml
.github/workflows/test.clients.python.yml
clients/python/.gitignore
clients/python/README.md
clients/python/moonstream/client.py
clients/python/moonstream/test_client.py
clients/python/setup.py
clients/python/tag.bash

Adds a Python client library for the Moonstream API.
The client library has unit tests:
```bash
cd clients/python
python -m unittest discover
```
Resolves https://github.com/bugout-dev/moonstream/milestone/19

Moonstream Python client library

---

crawlers/server/main.go
crawlers/server/sample.env
db/server/main.go
db/server/sample.env

CORS settings for status servers

---

backend/moonstream/api.py
backend/moonstream/providers/bugout.py
backend/moonstream/routes/whales.py

- Renamed `NftProvider` in to `PublicDataProvider` 
- Added `/whales` public endpoint
Test if API points work correctly

Whale watch backend changes 

---

crawlers/server/main.go
db/server/main.go

Fixed CORS check in go status servers

---

crawlers/mooncrawl/mooncrawl/ethcrawler.py

There was a mistake generating holes in blocks list

Fix sync blocks logic

---

frontend/pages/_app.js
frontend/pages/index.js

After demoing to people Ive noticed some slow loading, after short investigation appears that using dynamic imports was bad idea for `<head>` tag generation within Next SSG compilation step. I removed dynamic imports and as well some of unused preload components 
Also, not git related, but still worth to mention - Reduced size of product page images on AWS . 
Check in production your loading time

Improve loading speed

---

frontend/package.json
frontend/src/components/NewSubscription.js
frontend/src/components/RadioCard.js
frontend/src/components/SubscriptionsList.js
frontend/src/components/UploadABI.js
frontend/src/core/providers/OverlayProvider/constants.js
frontend/src/core/providers/OverlayProvider/index.js
frontend/yarn.lock

- in `/subscriptions` you can see `upload` buttons in `abi` column
- new modal type for uploading abi
- Verifying json
This is purely UI PR, no backend/logic implemented
Locally see that UI is OK
resolves #344

Abi upload with code editor block in modal

---

frontend/next.config.js
frontend/pages/docs.js
frontend/pages/index.js
frontend/pages/whitepapers.js
frontend/src/core/constants.js

react redoc, move text, add status page

---

backend/moonstream/routes/subscriptions.py

Add fix for ethereum_whalewatch wich not required address.

---

crawlers/deploy/ethereum-txpool.service

Fixed start of service for txpool crawler

Removed unnecessary flag at service crawler

---

frontend/src/components/TokensList.js

fix filter not woroking on tokens screen

---

frontend/pages/index.js

fix signup button

---

crawlers/deploy/polygon-synchronize.service
crawlers/mooncrawl/sample.env

Fixed typo in polygon crawlers

---

backend/moonstream/data.py
backend/moonstream/routes/dashboards.py

Add data links endpoint

---

frontend/pages/dashboard/[dashboardId].js
frontend/src/components/AccountIconButton.js
frontend/src/components/AddNewIconButton.js
frontend/src/components/Dashboard.js
frontend/src/components/RangeSelector.js
frontend/src/core/hooks/useDashboard.js
frontend/src/core/hooks/useWindowSize.js
frontend/src/core/providers/OverlayProvider/index.js
frontend/src/core/services/dashboard.service.js

- Ported nfts.js from `landing-improvements-alpha` to `Dashboard/[dashboardId].js Some functionality that has to be dynamic disabled for now until i try with real data
- Added ability to delete dashboard
- Added logic to refetch after dashboard created/deleted
- Added RangeSelector component
- Added WindowResized hook (part of ex nft.js )
Localhost create/delete dashboards, follow links on sidebar to open dashboards
#356

Dashboard component

---

crawlers/deploy/deploy.bash
crawlers/deploy/ethereum-missing.service
crawlers/deploy/ethereum-missing.timer
crawlers/deploy/polygon-missing.service
crawlers/deploy/polygon-missing.timer
crawlers/mooncrawl/mooncrawl/crawler.py

To automate missing block check.
Small changes

Missing block finder automatization

---

crawlers/deploy/ethereum-missing.service
crawlers/deploy/polygon-missing.service

Blocks missing instead of missing

---

frontend/pages/dashboard/[dashboardId].js
frontend/src/components/NewDashboard.js
frontend/src/components/Report.js
frontend/src/components/SubscriptionReport.js
frontend/src/core/services/dashboard.service.js

Front fixes

---

backend/moonstreamapi/actions.py
backend/moonstreamapi/routes/dashboards.py
crawlers/mooncrawl/mooncrawl/stats_worker/dashboard.py

Fix overwrite issue

---

crawlers/deploy/polygon-synchronize.service

Increased confirmations for polygon sync crawler

---

crawlers/deploy/deploy.bash

Fixed typo in deploy crawler polygon statistics

---

frontend/src/core/services/dashboard.service.js

Add slash dashboard

---

frontend/src/core/providers/OverlayProvider/index.js

Fixed sign up on more time for alpha

---

nodes/deploy/polygon/deploy.bash

During new node creation to prevent user-data script fall better to check file exist if not copy from S3

Prevent user-data script fall

---

nodes/deploy/polygon/deploy.bash

Reverts bugout-dev/moonstream#416

Revert "Prevent user-data script fall"

---

crawlers/mooncrawl/mooncrawl/stats_worker/dashboard.py

Extentions metrics

---

nodes/deploy/ethereum/deploy.bash
nodes/deploy/ethereum/geth.service

Removed specific listening port for ndoe server and don't start geth

---

crawlers/mooncrawl/mooncrawl/stats_worker/dashboard.py

Add correct datetime formating on dashboard worker.

---

frontend/src/components/SubscriptionReport.js

Add fix formating.

---

frontend/src/components/SubscriptionReport.js

scrollable

---

frontend/pages/stream/index.js
frontend/src/components/EntriesNavigation.js
frontend/src/components/Report.js
frontend/src/components/Sidebar.js
frontend/src/layouts/EntriesLayout.js

retuned stream page 
Launch locally and see if /stream page works

Return of the stream

---

frontend/src/core/providers/UIProvider/index.js

`/welcome` page was modified, and onboarding UX needs some extra love to be functional again. Becuase of that it redicrects to `/welcome` each time app is refreshed. Here I just removed redirect so it's easy implement back again
Run localy, go to your dashboard and try to reload page.

commented out redirect on onboarding not complete

---

frontend/src/components/RangeSelector.js

fix colors on range selector to work on active focus hover

use updated color keys in range selector styling

---

frontend/src/core/providers/OverlayProvider/index.js

this will correctly clear state when drawer cancel button is clicked in new dashboard creation

using correct callback to close newDashboard drawer

---

frontend/pages/welcome.js

improved content to explain how to build dashboard

Welcome page content improvements

---

frontend/src/components/Sidebar.js

Fixed  mobile sidebar not opening modal signup and login

fix login and signup modal call from  sidebar

---

frontend/pages/dashboard/[dashboardId].js
frontend/src/components/Report.js
frontend/src/components/SubscriptionReport.js

reduced margins and flexbasis, added some responsiveness
On mobile best : )

Imrove dashboard responsivness

---

frontend/pages/dashboard/[dashboardId].js
frontend/src/components/SubscriptionReport.js

better wrapping

---

frontend/src/components/Sidebar.js

reorder sidebar footer

---

frontend/pages/status/index.js
frontend/src/core/hooks/useStatus.js

Small improvements to organize code and show spinners while status is loading

Improve status page

---

crawlers/mooncrawl/mooncrawl/stats_worker/dashboard.py

Add custom tracking of hatched events.

---

backend/moonstreamapi/routes/dashboards.py
crawlers/mooncrawl/mooncrawl/stats_worker/dashboard.py

Add apply of filters wich in general depends on names of dashboard subscriptions.
Values filters not include.
Reformat code for get support of subscription wich not contain abi and only have set of generic methods.
Remove filtering labels by dates so if label vailabel in database and in filter/abi if no data for that labels query return zeros timesseries.

Add apply of filters.

---

frontend/src/components/NewDashboard.js

fixed abi upload button not working correctly in new dashboard drawer
resolves #455

fix abi upload from drawer

---

backend/moonstreamapi/data.py
backend/moonstreamapi/routes/dashboards.py

resolve https://github.com/bugout-dev/moonstream/issues/458

Add fixes for work with json data insted form data.

---

frontend/src/core/services/dashboard.service.js

Fix delete request to dashbord endpoint

---

backend/moonstreamapi/actions.py
backend/moonstreamapi/data.py
backend/moonstreamapi/routes/subscriptions.py

Add abi endpoint.

---

frontend/package.json
frontend/pages/status/index.js
frontend/sample.env
frontend/src/core/hooks/useStatus.js
frontend/src/core/services/status.service.js

Status page works with status endpoint `status.moonstream.to`
Tested

Extended status page with nodes blocks

---

crawlers/mooncrawl/mooncrawl/stats_worker/dashboard.py

Add next structure to dashboards stats:
```json
{
"latest_available_block": 22119823,
"latest_crawled_block": 22119756,
"earliest_crawled_block": 11029941
}
```
Generate stats dashboards. Polygon as example:
```bash
python -m mooncrawl.stats_worker.dashboard generate --blockchain polygon
```

Apply information about blocks to stats report.

---

frontend/pages/status/index.js

Trying to fix status page to check if `isLoading`

Fix status page to be undefined if isLoading

---

frontend/pages/status/index.js

Reverts bugout-dev/moonstream#485

Revert "Fix status page to be undefined if isLoading"

---

frontend/pages/status/index.js

Fixed geth -> bor at status page

---

backend/setup.py

Specified version of bugout at setup.py

---

backend/moonstreamapi/actions.py
frontend/src/components/NewDashboard.js

Add fix of keys.

---

backend/deploy/moonstreamapi.service

Moonstream api backend works via nginx with localhost and proxy headers

moonstreamapi service change to localhost

---

frontend/pages/team/index.js

Added Yhtyyar's surname

---

crawlers/deploy/polygon-synchronize.service

1 thread for polygon syncronization crawler is too slow.
Already in prod

Fix - Polygon syncronize crawler works in multi threads

---

crawlers/mooncrawl/mooncrawl/moonworm_crawler/crawler.py

Fixed typo while querying bugout

fixed job pickup

---

crawlers/mooncrawl/mooncrawl/moonworm_crawler/continuous_crawler.py
crawlers/mooncrawl/mooncrawl/moonworm_crawler/crawler.py

Fixed deduplication while picking up new jobs

fixed deduplication of abi

---

frontend/pages/dashboard/[dashboardId].js

Fix time range button not working in dashboard

---

frontend/pages/dashboard/[dashboardId].js

Day timerange as default.

---

backend/configs/sample.env
crawlers/deploy/deploy.bash
crawlers/deploy/mooncrawl.service

Endpoint for API handlers to execute crawlers with API
Locally

Moonstream crawlers service for HTTP API server

---

frontend/pages/index.js
frontend/pages/status/index.js
frontend/src/components/DragOnGrid.js
frontend/src/components/SchematicPlayground.js
frontend/src/core/services/dashboard.service.js

Improved flow diagram to display images instead of text

Flow diagram improvement

---

frontend/src/components/Footer.js

Automatically change copyright year

---

crawlers/mooncrawl/mooncrawl/stats_worker/dashboard.py

Dashboarsd transaction rollback

---

crawlers/mooncrawl/mooncrawl/stats_worker/dashboard.py

Remove transactions_in transactions_out value_in value_out stats generations metrics.
Save implementation in https://github.com/bugout-dev/moonstream/tree/generic-metrics-arhive

Remove heavy metrics generation.

---

crawlers/deploy/deploy.bash

Fix --no-block for statistic timer crawler

---

crawlers/deploy/mooncrawl.service
crawlers/deploy/polygon-statistics.timer

Increase service timer.

---

crawlers/mooncrawl/mooncrawl/stats_worker/dashboard.py

Remove address from special rule.

---

frontend/pages/dashboard/[dashboardId].js
frontend/src/components/Report.js
frontend/src/components/SubscriptionReport.js

added few checks for undefined before map

---

crawlers/deploy/ethereum-synchronize.service
crawlers/deploy/polygon-synchronize.service
nodes/deploy/ethereum/deploy.bash
nodes/deploy/polygon/deploy.bash

Heimalld from polygon node works via node balancer instead of direct one node.
Already in production

Heimdall now work via nodebalancer

---

nodes/deploy/polygon/bor.service

Fix for bor service variable

---

nodes/deploy/ethereum/deploy.bash
nodes/deploy/polygon/deploy.bash

Removed geth and bor status check to prevent script fall

---

nodes/deploy/ethereum/deploy.bash
nodes/deploy/polygon/deploy.bash

Checkenv cant find root home

---

nodes/deploy/ethereum/node-status.service

Typo at node status service file

---

crawlers/deploy/ethereum-missing.service
crawlers/deploy/ethereum-synchronize.service
crawlers/deploy/polygon-missing.service
crawlers/deploy/polygon-moonworm-crawler.service
crawlers/deploy/polygon-synchronize.service
crawlers/mooncrawl/mooncrawl/blockchain.py
crawlers/mooncrawl/mooncrawl/contract/cli.py
crawlers/mooncrawl/mooncrawl/crawler.py
crawlers/mooncrawl/mooncrawl/moonworm_crawler/cli.py
crawlers/mooncrawl/mooncrawl/moonworm_crawler/continuous_crawler.py
crawlers/mooncrawl/mooncrawl/nft/cli.py
crawlers/mooncrawl/mooncrawl/settings.py
crawlers/mooncrawl/mooncrawl/stats_worker/dashboard.py
nodes/node_balancer/cmd/middleware.go
nodes/node_balancer/configs/settings.go

In prospect node balancer will work for public access and it will require client token for authentication.
Tests at local

Client id to work with node balancer

---

crawlers/deploy/ethereum-missing.service
crawlers/deploy/ethereum-synchronize.service
crawlers/deploy/polygon-missing.service
crawlers/deploy/polygon-moonworm-crawler.service
crawlers/deploy/polygon-synchronize.service
crawlers/mooncrawl/mooncrawl/blockchain.py
crawlers/mooncrawl/mooncrawl/contract/cli.py
crawlers/mooncrawl/mooncrawl/crawler.py
crawlers/mooncrawl/mooncrawl/moonworm_crawler/cli.py
crawlers/mooncrawl/mooncrawl/moonworm_crawler/continuous_crawler.py
crawlers/mooncrawl/mooncrawl/nft/cli.py
crawlers/mooncrawl/mooncrawl/settings.py
crawlers/mooncrawl/mooncrawl/stats_worker/dashboard.py
nodes/node_balancer/cmd/middleware.go
nodes/node_balancer/configs/settings.go

Reverts bugout-dev/moonstream#539

Revert "Client id to work with node balancer"

---

frontend/src/components/Sidebar.js

keep year updated at sidebar footer copyright

---

crawlers/deploy/polygon-statistics.service
crawlers/deploy/polygon-statistics.timer

We update button there are no needs in dashboard frequently auto updates.
No need tests

Dasboard update timer modified from 15m -> 6h

---

backend/deploy/deploy.bash
crawlers/deploy/deploy.bash
nodes/deploy/deploy.bash
nodes/deploy/ethereum/geth.service
nodes/deploy/polygon/bor.service

In deploy scripts point to go root dir $HOME/ -> /root/

---

frontend/pages/index.js
frontend/src/Theme/Badge/index.js
frontend/src/components/SplitWithImage.js
frontend/src/components/TrustedBadge.js

initial alpha for update

---

frontend/pages/index.js
frontend/src/components/SplitWithImage.js
frontend/src/components/TrustedBadge.js

review updates

---

frontend/pages/index.js
frontend/src/Theme/Badge/index.js
frontend/src/components/SplitWithImage.js
frontend/src/components/TrustedBadge.js

Landing page update

---

frontend/src/core/constants.js

change metatags

---

frontend/pages/index.js

updated number of value trough our contracts

---

frontend/pages/index.js
frontend/pages/team/index.js

team page update

---

frontend/pages/index.js
frontend/pages/team/index.js
frontend/src/components/TrustedBadge.js

update landing page

---

frontend/pages/status/index.js
frontend/sample.env
frontend/src/core/hooks/useStatus.js
frontend/src/core/services/status.service.js

Increased detailing of status page
Tested locally

Updated status page for monitoring server

---

frontend/pages/index.js
frontend/pages/status/index.js

Mixpanel improvements

---

frontend/src/components/SplitWithImage.js

better mixpanel props

---

db/server/cmd/data.go
db/server/cmd/routes.go

Getting polygon_block_latest_label_moonworm_alpha for status db

---

crawlers/mooncrawl/mooncrawl/moonworm_crawler/cli.py
crawlers/mooncrawl/mooncrawl/moonworm_crawler/crawler.py

When function call crawler job is created, checking function signature if this job already exists

checking function abi before creating job

---

crawlers/mooncrawl/mooncrawl/moonworm_crawler/cli.py
crawlers/mooncrawl/mooncrawl/moonworm_crawler/crawler.py

Reverts bugout-dev/moonstream#583

Revert "checking function abi before creating job"

---

frontend/src/core/providers/AnalyticsProvider/index.js

added schema version to mixpanel analytics

---

frontend/src/components/SubscriptionsList.js

Removed section 2 from subscriptions mobile view.

Removed Section 2 from mobile subscriptions view.

---

frontend/src/components/Sidebar.js

Sidebar should close after a link click in mobile view.
Tested locally.

Toggle sidebar after link click in mobile view.

---

nodes/deploy/xdai/deploy.bash
nodes/deploy/xdai/node-status.service
nodes/deploy/xdai/xdai.service
nodes/server/cmd/routes.go
nodes/server/cmd/server.go

xDai node deployment

---

nodes/.gitignore
nodes/deploy/deploy.bash
nodes/deploy/node-balancer-config.txt
nodes/deploy/node-balancer.service
nodes/node_balancer/cmd/cli.go
nodes/node_balancer/cmd/clients.go
nodes/node_balancer/cmd/routes.go
nodes/node_balancer/cmd/server.go
nodes/node_balancer/configs/settings.go
nodes/node_balancer/configs/version.go
nodes/node_balancer/dev.sh
nodes/node_balancer/main.go

Removed hardcoded node uris and added xdai blockchain
Tested

Cli config file for node list setup

---

db/scm.nix

Removed all refs

---

crawlers/deploy/deploy-moonworm-cu.bash
crawlers/deploy/moonworm-unicorns-mainnet.service

Automated moonworm cu crawler deployment
Tested locally

Auto deploy of moonworm cu mainnet crawler

---

db/moonstreamdb/blockchain.py
db/moonstreamdb/version.py

XDai database blockchain update to support XDai

---

crawlers/deploy/deploy.bash
crawlers/deploy/xdai-moonworm-crawler.service

XDai moonworm crawler service

---

backend/moonstreamapi/routes/streams.py

Expected speed will be increased.

Using replica read only to get subscription events

---

backend/moonstreamapi/routes/streams.py

Reverts bugout-dev/moonstream#622

Revert "Using replica read only to get subscription events"

---

nodes/node_balancer/cmd/clients.go
nodes/node_balancer/cmd/middleware.go
nodes/node_balancer/cmd/server.go
nodes/node_balancer/configs/settings.go

Caching behaviour in middleware to reduce load on Brood.
Locally

Node balancer cache for access_id

---

db/scm.nix
db/sync_conf.yml

Updated commit with scematic XDai tables
Locally

XDai schematic upgrade

---

crawlers/mooncrawl/mooncrawl/moonworm_crawler/continuous_crawler.py
crawlers/mooncrawl/mooncrawl/moonworm_crawler/function_call_crawler.py

Pointing to correct network at moonworm_crawler

---

nodes/.gitignore
nodes/deploy/deploy.bash
nodes/deploy/node-balancer-config.txt
nodes/deploy/node-balancer.service
nodes/deploy/nodebalancer.service
nodes/node_balancer/cmd/cli.go
nodes/node_balancer/cmd/nodebalancer/balancer.go
nodes/node_balancer/cmd/nodebalancer/blockchain.go
nodes/node_balancer/cmd/nodebalancer/cli.go
nodes/node_balancer/cmd/nodebalancer/clients.go
nodes/node_balancer/cmd/nodebalancer/clients_test.go
nodes/node_balancer/cmd/nodebalancer/configs.go
nodes/node_balancer/cmd/nodebalancer/db.go
nodes/node_balancer/cmd/nodebalancer/main.go
nodes/node_balancer/cmd/nodebalancer/middleware.go
nodes/node_balancer/cmd/nodebalancer/routes.go
nodes/node_balancer/cmd/nodebalancer/server.go
nodes/node_balancer/cmd/nodebalancer/version.go
nodes/node_balancer/configs/settings.go
nodes/node_balancer/configs/version.go
nodes/node_balancer/dev.sh
nodes/node_balancer/main.go
nodes/node_balancer/sample.env

External nodes support

---

crawlers/mooncrawl/mooncrawl/generic_crawler/cli.py
crawlers/mooncrawl/mooncrawl/moonworm_crawler/cli.py
crawlers/mooncrawl/mooncrawl/moonworm_crawler/continuous_crawler.py
crawlers/mooncrawl/mooncrawl/moonworm_crawler/crawler.py
crawlers/mooncrawl/mooncrawl/moonworm_crawler/db.py
crawlers/mooncrawl/mooncrawl/moonworm_crawler/event_crawler.py
crawlers/mooncrawl/mooncrawl/moonworm_crawler/historical_crawler.py

Added historical crawler
Example:
```bash
moonworm-crawler historical-crawl --address 0x431CD3C9AC9Fc73644BF68bF5691f4B83F9E104f --poa --end 25329797 --max-blocks-batch 5000 --only-events -b polygon
```

Moonworm historical crawler

---

nodes/node_balancer/cmd/nodebalancer/middleware.go
nodes/node_balancer/cmd/nodebalancer/routes.go

Support of batch endpoints.
Tested with sync and bot crawlers locally

Support of list of json rpc requests

---

nodes/node_balancer/cmd/nodebalancer/balancer.go
nodes/node_balancer/cmd/nodebalancer/configs.go

To prevent long future overflow.
Tested locally

Callcounter reset when 10mln

---

nodes/node_balancer/cmd/nodebalancer/clients.go
nodes/node_balancer/cmd/nodebalancer/clients_test.go
nodes/node_balancer/cmd/nodebalancer/configs.go
nodes/node_balancer/cmd/nodebalancer/routes.go
nodes/node_balancer/cmd/nodebalancer/server.go
nodes/node_balancer/cmd/nodebalancer/version.go

Previously all blockchains were hardcoded.
Require re-write of `clients_test.go`
Tested locally.

Generate pool of available blockchains from config

---

crawlers/mooncrawl/mooncrawl/stats_worker/queries.py

All not string and int columns transform to string.

---

db/scm.nix

Small changes for scm db
tested on prod

Sourcing env file with nix start and new commit with fix

---

db/moonstreamdb/db.py
db/moonstreamdb/version.py

Add pool pre ping parameter.

---

db/scm.nix

Schematic migrated from gitlab
In prod

Correct git path for scm mdp repo

---

frontend/pages/index.js
frontend/src/core/constants.js

Remove 'no code' from landing page and metadata.

---

crawlers/mooncrawl/mooncrawl/state_crawler/cli.py

Add logging.

---

frontend/.eslintrc.json
frontend/pages/contact/index.js
frontend/pages/team/index.js
frontend/src/components/TeamCard.js

Updated team member images. Added Ishkhan. Removed Tim. Moved Sam to DAO.

Updates to team page.

---

crawlers/deploy/deploy.bash
crawlers/deploy/polygon-state-clean.service
crawlers/deploy/polygon-state-clean.timer
crawlers/mooncrawl/mooncrawl/state_crawler/cli.py
crawlers/mooncrawl/mooncrawl/state_crawler/db.py

```bash 
state-crawler clean-state-labels -b polygon -N 10000
```

Add remove worker

---

nodes/deploy/ethereum/deploy.bash
nodes/deploy/ethereum/geth.service
nodes/deploy/ethereum/lighthousebeacon.service

Support after merge ethereum node

Lighthouse eth node service

---

crawlers/mooncrawl/mooncrawl/moonworm_crawler/cli.py

```bash
moonworm-crawler --access-id $NB_CONTROLLER_ACCESS_ID historical-crawl -s 32606899 -e 32609000 -b polygon --poa --force
```

Remove address requirements for historical_crawler.

---

crawlers/deploy/ethereum-missing.timer
crawlers/deploy/ethereum-trending.timer
crawlers/deploy/polygon-metadata.timer
crawlers/deploy/polygon-missing.timer
crawlers/deploy/polygon-state-clean.timer
crawlers/deploy/polygon-state.timer
crawlers/deploy/polygon-statistics.timer
crawlers/deploy/xdai-missing.timer
crawlers/deploy/xdai-statistics.timer

Changes to avoid statement timeout response from database.

Different timer on boot start time

---

crawlers/mooncrawl/mooncrawl/moonworm_crawler/event_crawler.py
crawlers/mooncrawl/mooncrawl/moonworm_crawler/function_call_crawler.py
crawlers/mooncrawl/mooncrawl/moonworm_crawler/historical_crawler.py
crawlers/mooncrawl/mooncrawl/version.py
crawlers/mooncrawl/setup.py

Add autoscale to historical crawl.

---

crawlers/mooncrawl/mooncrawl/moonworm_crawler/historical_crawler.py

Fix missing rollback.

---

crawlers/mooncrawl/mooncrawl/blockchain.py
crawlers/mooncrawl/mooncrawl/settings.py

Add enviroment variable `WEB3_CLIENT_REQUEST_TIMEOUT_SECONDS`

Add timeout for HTTPProvider.

---

frontend/pages/contact/index.js
frontend/pages/index.js

Fixed cropping issue on iphone size.

---

crawlers/mooncrawl/mooncrawl/moonworm_crawler/cli.py

Add convert args address to checksum address.

---

crawlers/deploy/deploy.bash
crawlers/deploy/mumbai-missing.service
crawlers/deploy/mumbai-missing.timer
crawlers/deploy/mumbai-synchronize.service

Mumbai basic crawlers to deploy.
Tested locally.

Mumbai sync and missing crawlers

---

frontend/pages/dashboard/[dashboardId].js
frontend/pages/welcome.js
frontend/src/components/AccountIconButton.js
frontend/src/components/AddNewIconButton.js
frontend/src/components/AppNavbar.js
frontend/src/components/LandingNavbar.js
frontend/src/components/Report.js
frontend/src/components/SubscriptionReport.js
frontend/src/core/providers/OverlayProvider/index.js
frontend/src/layouts/AppLayout.js

Fixing layout colors when logged in.

---

frontend/src/components/ConfirmationRequest.js

Changing texts color on the ConfirmationRequest popover
Click delete button in the subscriptions list

fixing white on white text

---

backend/deploy/deploy.bash
backend/deploy/moonstream.service
crawlers/deploy/deploy.bash

- Migrated deployment to checkenv
- Backend working under regular user

Deployment upgrades to work with systems

---

backend/deploy/deploy.bash
crawlers/deploy/deploy.bash

Create dir for env vars

---

backend/deploy/deploy.bash

Fixed user go dir in deployment

---

frontend/pages/contact/index.js
frontend/src/components/EntriesNavigation.js
frontend/src/components/Sidebar.js

Changing Contact Form background color to make text more visible.
Changing text color on Streams Filter Drawer
also changing logo cursor in sidebar to pointer

Fix text color

---

crawlers/deploy/polygon-cu-reports-tokenonomics.service

Updated service file for cu queries crawler

---

crawlers/mooncrawl/mooncrawl/cu_reports_crawler/cli.py

Replace prints via logger.

---

frontend/pages/status/index.js
frontend/pages/whitepapers.js
frontend/src/components/Scrollable.js
frontend/src/components/TeamCard.js

Fixing Navbar disappearance on iOS when page bounces after scroll
Some pages colors 
Open on the iOS device, scroll down to make page bounce

Mobile menu layout

---

crawlers/deploy/deploy.bash
crawlers/deploy/ethereum-moonworm-crawler.service

Moonworm crawlers for ethereum

---

crawlers/mooncrawl/mooncrawl/api.py
crawlers/mooncrawl/mooncrawl/stats_worker/queries.py

Fix passing list as sql parameter

---

crawlers/mooncrawl/mooncrawl/moonworm_crawler/continuous_crawler.py

Add rollback.

---

crawlers/mooncrawl/mooncrawl/blockchain.py

According with merge json-rpc request removed unused keys for gnosis block.

Fix deprecated keys for gnosis

---

crawlers/deploy/deploy.bash

Add deploy changes

---

frontend/pages/features/index.js
frontend/pages/index.js
frontend/pages/privacy-policy/index.js
frontend/pages/team/index.js
frontend/pages/tos/index.js
frontend/pages/whitepapers.js
frontend/src/Theme/Button/index.js
frontend/src/components/AccountIconButton.js
frontend/src/components/Footer.js
frontend/src/components/LandingBarMobile.js
frontend/src/components/LandingNavbar.js
frontend/src/components/Navbar.js
frontend/src/components/TeamCard.js
frontend/src/components/molecules/WhitepaperCard.js
frontend/src/layouts/InfoPageLayout.js
frontend/src/layouts/WideInfoPage.js

Landing pages layouts, new view for whitepappers

Landing pages

---

frontend/pages/whitepapers.js
frontend/src/components/LandingNavbar.js

Fix navbar  and whitepapper card width

fixing navbar and whitepapper mobile

---

crawlers/deploy/deploy-moonworm-cu.bash
crawlers/deploy/deploy.bash
crawlers/deploy/ethereum-missing.service
crawlers/deploy/ethereum-moonworm-crawler.service
crawlers/deploy/ethereum-synchronize.service
crawlers/deploy/ethereum-trending.service
crawlers/deploy/ethereum-txpool.service
crawlers/deploy/mooncrawl.service
crawlers/deploy/moonworm-unicorns-mainnet.service
crawlers/deploy/mumbai-metadata.service
crawlers/deploy/mumbai-missing.service
crawlers/deploy/mumbai-moonworm-crawler.service
crawlers/deploy/mumbai-state-clean.service
crawlers/deploy/mumbai-state.service
crawlers/deploy/mumbai-synchronize.service
crawlers/deploy/polygon-cu-reports-tokenonomics.service
crawlers/deploy/polygon-metadata.service
crawlers/deploy/polygon-missing.service
crawlers/deploy/polygon-moonworm-crawler.service
crawlers/deploy/polygon-state-clean.service
crawlers/deploy/polygon-state.service
crawlers/deploy/polygon-statistics.service
crawlers/deploy/polygon-synchronize.service
crawlers/deploy/polygon-txpool.service
crawlers/deploy/xdai-missing.service
crawlers/deploy/xdai-moonworm-crawler.service
crawlers/deploy/xdai-statistics.service
crawlers/deploy/xdai-synchronize.service

Support of systems deployment

---

crawlers/deploy/deploy-moonworm-cu.bash

`watch-cu` unsupported in new versions

Use 0.2.4 moonworm for watch-cu crawler

---

crawlers/mooncrawl/mooncrawl/cu_reports_crawler/cli.py

Add json upload.
Add logging.
run
```
custom-crawler cu-reports --moonstream-token $MOONSTREAM_PUBLIC_QUERIES_TOKEN generate-nft-dashboar
```
check:
`data.moonstream.to/queries/cu_nft_dashboard_data/data.json`
and
`data.moonstream.to/queries/cu_nft_dashboard_data/data.csv`

Add json upload.

---

crawlers/deploy/deploy.bash
crawlers/mooncrawl/setup.py

Fixed typo in deploy crawlers and version of moonworm

---

crawlers/mooncrawl/mooncrawl/stats_worker/queries.py

Fix text clause miss for sqlalchemy 2.0.4 and dict converting.

---

crawlers/mooncrawl/mooncrawl/metadata_crawler/db.py
crawlers/mooncrawl/mooncrawl/version.py

Fix metadata crawler

---

crawlers/mooncrawl/mooncrawl/blockchain.py
crawlers/mooncrawl/mooncrawl/contract/cli.py
crawlers/mooncrawl/mooncrawl/db.py
crawlers/mooncrawl/mooncrawl/esd.py
crawlers/mooncrawl/mooncrawl/etherscan.py
crawlers/mooncrawl/mooncrawl/generic_crawler/cli.py
crawlers/mooncrawl/mooncrawl/identity.py
crawlers/mooncrawl/mooncrawl/metadata_crawler/cli.py
crawlers/mooncrawl/mooncrawl/moonworm_crawler/cli.py
crawlers/mooncrawl/mooncrawl/settings.py
crawlers/mooncrawl/mooncrawl/state_crawler/cli.py
crawlers/mooncrawl/mooncrawl/stats_worker/dashboard.py
crawlers/mooncrawl/mooncrawl/stats_worker/queries.py

Some crawlers use short backend timeout, which is wrong and not let to finish long queries.

Custom engine for all crawlers with specific timeout

---

crawlers/deploy/wyrm-moonworm-crawler.service

Add start block as 0.

---

crawlers/deploy/deploy.bash
crawlers/deploy/wyrm-missing.service
crawlers/deploy/wyrm-missing.timer
crawlers/deploy/wyrm-statistics.service
crawlers/deploy/wyrm-statistics.timer
crawlers/deploy/wyrm-synchronize.service
crawlers/mooncrawl/mooncrawl/blockchain.py
crawlers/mooncrawl/mooncrawl/crawler.py

Wyrm blocks transactions

---

crawlers/deploy/polygon-synchronize.service

Set polygon confirmations to sync crawler to 40

---

crawlers/deploy/mumbai-synchronize.service

Set confirmation blocks for mumbai crawler 20

---

crawlers/deploy/mumbai-moonworm-crawler.service

Mumbai moonworm-crawler conformations set to 40

---

backend/setup.py
crawlers/mooncrawl/setup.py

Bump version.

---

frontend/src/components/SubscriptionCard.js

Turned off Uppload for frontend ABI

---

backend/moonstreamapi/admin/cli.py
backend/moonstreamapi/admin/migrations/generate_entity_subscriptions.py

For reproduce state of issue you need:
Localy run migration from [PR](https://github.com/bugout-dev/moonstream/pull/751) with entity client version <= 0.0.3
That reproduce state of nested keys.
```
mnstr migrations run --id 20230501 --step fix_duplicates_keys_in_entity_subscription
```
```
delete
from
journal_entries
where
journal_id in (
select
id
from
journals
where
name like 'subscriptions_%'
)
and id in (
select
journal_entries.id
from
journal_entries
JOIN journal_entry_tags on journal_entries.id = journal_entry_tags.journal_entry_id
WHERE
journal_entry_tags.tag in ('type:copy_of_malformed_entity_20230213')
);
```
```
python -m spire.journal.search synchronize --journal-id any --es-index bugout-main
```

Fix entities migration.

---

backend/setup.py
crawlers/mooncrawl/setup.py

New version for entity client

---

backend/moonstreamapi/actions.py
backend/moonstreamapi/data.py
backend/moonstreamapi/routes/queries.py
backend/moonstreamapi/routes/subscriptions.py
backend/moonstreamapi/routes/users.py
backend/moonstreamapi/version.py

Extend get query endpoint.

---

frontend/pages/team/index.js
frontend/src/components/TeamCard.js

Adding Anton's card to the team page

adding Anton's card

---

crawlers/deploy/polygon-moonworm-crawler.service

Change polygon crawler parameters.

---

nodes/node_balancer/cmd/nodebalancer/configs.go

Hardcoded auth url for nb

---

nodes/node_balancer/cmd/nodebalancer/middleware.go
nodes/node_balancer/cmd/nodebalancer/server.go

Fixed nodebalancer cors post support

---

crawlers/mooncrawl/mooncrawl/moonworm_crawler/crawler.py

Fix incorrect using of entries object for function call.
And fix refetch(merge jobs logic) for events.

Fix historical function crawl

---

moonstreamapi/moonstreamapi/data.py
moonstreamapi/moonstreamapi/routes/queries.py

/query was not handle templates and only user query.

Add fix for name resolurtion in /query.

---

engineapi/engineapi/actions.py
engineapi/engineapi/cli.py
engineapi/engineapi/data.py
engineapi/engineapi/routes/admin.py
engineapi/engineapi/routes/leaderboard.py

Add init version of get leaderboard endpoints.

---

engineapi/engineapi/api.py
engineapi/engineapi/routes/admin.py
engineapi/engineapi/routes/configs.py
engineapi/engineapi/routes/dropper.py
engineapi/engineapi/routes/leaderboard.py
engineapi/engineapi/routes/metatx.py
engineapi/engineapi/routes/play.py

Reverts moonstream-to/api#835
Did not worked.

Revert "Emergency fix CORS back"

---

clients/python/README.md
docs/architecture.md
nodebalancer/README.md

Fix: typos

---

moonstreamapi/moonstreamapi/data.py
moonstreamapi/moonstreamapi/routes/subscriptions.py
moonstreamapi/moonstreamapi/settings.py

Revert "Add tags and descriptions"

---

moonstreamapi/moonstreamapi/data.py
moonstreamapi/moonstreamapi/routes/subscriptions.py
moonstreamapi/moonstreamapi/settings.py

Add tags and descriptions after revert

---

crawlers/mooncrawl/mooncrawl/metadata_crawler/cli.py
crawlers/mooncrawl/mooncrawl/metadata_crawler/db.py

Fix crawl leak and query overlap.

Refactor metadata crawler.

---

engineapi/engineapi/actions.py
engineapi/engineapi/data.py
engineapi/engineapi/routes/leaderboard.py

Goal add endpoint to create, read, update, delete leaderboard:
```
POST http://127.0.0.1:7191/leaderboard
Authorization: Bearer <moonstream-token>
Content-Type: application/json
{
"title": "",
"description": ""
}
```
response:
```
{
"id": "8fe5c615-5b9d-4f53-900d-babcf9529919",
"title": "",
"description": "",
"resource_id": "e556fe8d-7309-40b9-aed5-6b001d6efd24",
"created_at": "2023-08-10T16:03:35.417060+03:00",
"updated_at": "2023-08-10T16:03:40.961683+03:00"
}
```
```
PUT http://127.0.0.1:7191/leaderboard/8fe5c615-5b9d-4f53-900d-babcf9529919
Authorization: Bearer <moonstream-token>
Content-Type: application/json
{
"title": "title",
"description": "description"
}
```
response:
```
{
"id": "8fe5c615-5b9d-4f53-900d-babcf9529919",
"title": "title",
"description": "description", …
```

Manage leaderboards

---

engineapi/deploy/deploy.bash
engineapi/deploy/engine-origins-sync.service
engineapi/deploy/engine-origins-sync.timer
engineapi/engineapi/routes/configs.py

Synchronize applied origins on each server
Tested locally

CORS origins synchronize service

---

nodebalancer/cmd/nodebalancer/blockchain.go
nodebalancer/cmd/nodebalancer/middleware.go
nodebalancer/cmd/nodebalancer/server.go

Support metamask, fixed path url lose when working with infura

Nb metamask support and small fixes

---

crawlers/mooncrawl/mooncrawl/state_crawler/jobs/mumbai-jobs.json
crawlers/mooncrawl/mooncrawl/state_crawler/jobs/polygon-jobs.json

Updated Mumbai job, and added Polygon mainnet job.

Jobs for Twilight Tactics

---

engineapi/engineapi/actions.py
engineapi/engineapi/routes/leaderboard.py

```
GET http://127.0.0.1:7191/leaderboard/scores?leaderboard_id=c0f3d66e-3b6c-4acc-83ee-b782f9fc2ea0&address=0x0000000000000000000000000000000000000001
```

Add get score endpoint.

---

nodebalancer/cmd/nodebalancer/balancer.go
nodebalancer/cmd/nodebalancer/configs.go
nodebalancer/cmd/nodebalancer/middleware.go
nodebalancer/cmd/nodebalancer/server.go

Fix cors and starknet sepolia support

---

engineapi/engineapi/actions.py
engineapi/engineapi/routes/leaderboard.py

```http
GET http://127.0.0.1:7191/leaderboard/?leaderboard_id=cc9353bf-df40-4e66-beec-2473a055184a&points_data.magical_chest_opens_points=80
```
API look for query parameter starting with `points_data.` and compile them to points_data dict.

Add leaderboard key value filter.

---

crawlers/mooncrawl/mooncrawl/moonworm_crawler/continuous_crawler.py
crawlers/mooncrawl/mooncrawl/moonworm_crawler/db.py
crawlers/mooncrawl/mooncrawl/moonworm_crawler/historical_crawler.py
crawlers/mooncrawl/mooncrawl/version.py

- Added Batch insert
- Replace IN with VALUES clause for deduplication and escape IN condition limit and optimize index usage.
Test
Moonworm crawler
```
moonworm-crawler --access-id "${NB_CONTROLLER_ACCESS_ID}" crawl -b polygon  --confirmations 50 --min-blocks-batch 20
```
Historical crawler
```
// Full recrawl
moonworm-crawler historical-crawl -s 48690611 -e 48647996 --force --blockchain-type polygon
```

Moonworm crawler fixes

---

nodebalancer/cmd/nodebalancer/server.go
nodebalancer/cmd/nodebalancer/version.go

Removed headers from proxy API

Removed nb headers duplication
