moonstream-to/api

backend/moonstream/routes/subscriptions.py, backend/moonstream/settings.py
Fixes mypy error where mypy couldn't understand that `MOONSTREAM_APPLICATION_ID` was not `Optional[str]` but rather a `str`.
From `backend/` with virtualenv activated:
```
mypy moonstream/
```
Should exit 0
=> Fixed small mypy issue when working with application_id

crawlers/moonstreamcrawlers/cli.py, crawlers/moonstreamcrawlers/esd.py, crawlers/moonstreamcrawlers/ethereum.py
Adds a `--start` argument to `blocks synchronize`. This allows us to start constant synchronization with the latest state of the blockchain from a given starting block.
Also adds support for HTTP providers for the Web3 connection.
Run them locally.
Resolves https://github.com/bugout-dev/moonstream/issues/36
=> Crawlers ethcrawler sync

crawlers/moonstreamcrawlers/cli.py, crawlers/moonstreamcrawlers/ethereum.py, crawlers/moonstreamcrawlers/test_cli.py
`--order {asc|desc}` with default `desc`
`--jobs` overrides `MOONSTREAM_CRAWL_WORKERS` environment variable from command line.
Test manually. @kompotkot and I ran these commands on Pi.
=> Added "--order" and "--jobs" arguments to "ethcrawler blocks synchronize"

frontend/pages/stream/[entryId].js, frontend/src/components/TxInfo.js, frontend/src/core/hooks/useTxInfo.js
Changes `gas limit` label under `gas` in txinfo component to `amount of gas used in transaction`
Fixes bug when `currentTransaction` is null
Resolves #82
=> Improving txinfo

crawlers/deploy/ethereum-trending.service, crawlers/deploy/ethereum-trending.timer, crawlers/mooncrawl/ethcrawler.py, crawlers/mooncrawl/ethereum.py
This PR adds a systemd service and timer for the trending ethereum addresses crawl.
It also modifies the `ethcrawler trending` CLI a bit to make it easier to invoke as a systemd unit (mostly involving putting sane defaults).
Run manually
https://github.com/bugout-dev/moonstream/issues/83
=> Systemd service and timer definition for "ethcrawler trending" crawl

frontend/pages/stream/index.js, frontend/pages/subscriptions.js, frontend/src/components/AppNavbar.js, frontend/src/components/EntriesNavigation.js, frontend/src/components/SteamEntryDetails.js, frontend/src/components/StreamEntry.js, frontend/src/components/TxInfo.js, frontend/src/core/hooks/useStream.js, frontend/src/core/hooks/useTxInfo.js, frontend/src/core/providers/UIProvider/index.js, frontend/src/layouts/EntriesLayout.js, frontend/styles/styles.css
- Cards colors
- Added nonce info in card
- Cards bottom is now flexbox
- Changed detail button color to `secondary`
- In Desktop view list of cards takes now 55% of screen, rest 45% takes side view 
- Sideview when no entry is selected is onboarding experience
- Added colors matching with active users subscription address colors. It will appear as background of an addresss 
- Simplified UI context to monitor state of UI in `/steam`: switching any state happens now via `setEntryDetailView`, when loading new transaction just`setCurrentTransaction`.  `setEntriesViewMode` is not exported anymore and being managed by internal UI context useEffects. 
-  Removed `entryId` from UI context as it's not being used. If need to get entryId from context - use `currentTransaction` object to set/get it …
=> Cards improvement

frontend/src/core/hooks/useStream.js
While testing, I had set the default stream query to `type:ethereum_whalewatch`. This is not the correct behavior in production and shows an empty stream for anyone not subscriped to `ethereum_whalewatch` events.
🤷
=> Fixed default stream query

backend/moonstream/data.py, frontend/pages/stream/index.js, frontend/src/core/hooks/useTxInfo.js
Also fixed request body on `/txinfo/ethereum_blockchain`.
This PR fixes the issue introduced by the event providers PR in which transaction information was not displaying on the stream entry details view.
It also fixes an inconsistency in the `/txinfo/ethereum_blockchain` API endpoint about the casing of the `gas_price` paramter in the request body.
Finally, it adds some null checks on the `ui` state. This is because the edited lines were causing errors in the frontend during development and could potentially cause errors in production as well.
Run locally.
Resolves #170
=> Fixed transaction information service on frontend

db/deploy/deploy.bash
When instance execute startup script it missing $HOME variable and because of it also missing $GOPATH.
Tested
=> HOME path missing when building with go deployment script

crawlers/mooncrawl/mooncrawl/ethcrawler.py
Syncronization command to add blocks with 6 blocks delay is:
```python
python -m mooncrawl.ethcrawler blocks synchronize -c 6 -j 1
```
Tested manually
=> Option to run block sync from current block at Ethereum

backend/moonstream/settings.py, frontend/src/components/EntriesNavigation.js, frontend/src/core/hooks/useStream.js
Add adition state to use effect on EntriesNavigator wich wait state when cache still empty list but we get `olderEvent.event_timestamp` have flag wich protect from execution that if state again maybe unrequired need check later.
Fix `settings.py` variable must be set error.
=> Add load older events in second request.

frontend/pages/_app.js, frontend/pages/entry-point.js, frontend/src/layouts/EntryPointLayout.js
Entry point for AWS now is `/entry-point/index.html` 
When redirected to, useEffect will store flag in local storage and 
`_app` will delete it after any other than `/entry-point` page is loaded
Deploy, Try to go to correct way - it should work. 
Try to go to nonexisting route - it should redirect to `404` page 
finally resolves #60
=> solve circular redirects

frontend/src/components/SplitWithImage.js
On mobile phone images of `<SplitWithImage />` scaled wrongly, fixed that
=> better image sizing on SplitWithImage components

frontend/pages/dashboard/[dashboardId].js, frontend/src/components/SubscriptionReport.js
Query keys were defined as randomly generated uuids, i changed those to be `dashboardId` and `timeRange`
This should make query key correspond to time range and dashboard as it should be. 
Run and test that s3 objects is being pulled only once 
resolve https://github.com/bugout-dev/moonstream/issues/464
=> fix query keys to be correct to stop refetches

backend/setup.py
Force `moonstreamdb>=0.2.2` in backend `setup.py`.
=> Force moonstreamdb>=0.2.2 to fix Moonstream API failures

crawlers/mooncrawl/mooncrawl/moonworm_crawler/cli.py, crawlers/mooncrawl/mooncrawl/moonworm_crawler/continuous_crawler.py, crawlers/mooncrawl/mooncrawl/moonworm_crawler/crawler.py, crawlers/mooncrawl/mooncrawl/moonworm_crawler/db.py, crawlers/mooncrawl/mooncrawl/version.py, crawlers/mooncrawl/setup.py
1. Crawler now will save labels once in `heartbeat_interval` (default 1 min)
2. Confirmations count increased to 175, so `moonworm-crawler` will be slower that blocks crawler and can use db more frequently
=> Continuous crawler batch saving

crawlers/mooncrawl/mooncrawl/moonworm_crawler/cli.py, crawlers/mooncrawl/mooncrawl/moonworm_crawler/continuous_crawler.py
There was the bug in the logic of the `sleep_time` which was added to decrease the pressure to the node.
The bug was : `The sleep time was only increasing, but never decreasing, so sleep_time could become ~1-2 hours`
removed exponential increase of the sleep time. added sleep time decrease.
=> fixed sleep time bug

crawlers/mooncrawl/mooncrawl/blockchain.py, crawlers/mooncrawl/mooncrawl/version.py
Request:
```
--data-raw '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x161cb42", true],"id":1}'
```
Response from XDai node running as Nethermind client locally, access via json rpc:
```bash
{
"hash": "0x377b4d02f5d655a3747c28c4ba1585b94ac32ff04e834b87eed389946bac1d5d",
"data": "0x74759ae40000000000000000000000000000000000000000000000000000000000000f130000000000000000000000000000000000000000000000000000000000000f130000000000000000000000000000000000000000000000000000000002f572400000000000000000000000000000000000000000000000000000000000000f13",
"input": "0x74759ae40000000000000000000000000000000000000000000000000000000000000f130000000000000000000000000000000000000000000000000000000000000f130000000000000000000000000000000000000000000000000000000002f5724000000000000000000000000 …
```
=> There is no need of data key at tx

nodes/node_balancer/README.md, nodes/node_balancer/cmd/nodebalancer/balancer.go, nodes/node_balancer/cmd/nodebalancer/cli.go, nodes/node_balancer/cmd/nodebalancer/clients_test.go, nodes/node_balancer/cmd/nodebalancer/configs.go, nodes/node_balancer/cmd/nodebalancer/middleware.go, nodes/node_balancer/cmd/nodebalancer/routes.go, nodes/node_balancer/cmd/nodebalancer/server.go, nodes/node_balancer/cmd/nodebalancer/version.go, nodes/node_balancer/go.mod, nodes/node_balancer/sample.env
Nobebalancer support of filter by tag.
Tested locally
=> Supports tags filter for nodes

crawlers/mooncrawl/mooncrawl/api.py, crawlers/mooncrawl/mooncrawl/cu_reports_crawler/cli.py, crawlers/mooncrawl/mooncrawl/data.py, crawlers/mooncrawl/mooncrawl/generic_crawler/base.py, crawlers/mooncrawl/mooncrawl/identity.py, crawlers/mooncrawl/mooncrawl/metadata_crawler/cli.py, crawlers/mooncrawl/mooncrawl/metadata_crawler/db.py, crawlers/mooncrawl/mooncrawl/moonworm_crawler/cli.py, crawlers/mooncrawl/mooncrawl/moonworm_crawler/crawler.py, crawlers/mooncrawl/mooncrawl/moonworm_crawler/db.py, crawlers/mooncrawl/mooncrawl/moonworm_crawler/event_crawler.py, crawlers/mooncrawl/mooncrawl/moonworm_crawler/function_call_crawler.py, crawlers/mooncrawl/mooncrawl/moonworm_crawler/historical_crawler.py, crawlers/mooncrawl/mooncrawl/state_crawler/cli.py, crawlers/mooncrawl/mooncrawl/state_crawler/db.py, crawlers/mooncrawl/mooncrawl/state_crawler/web3_util.py, crawlers/mooncrawl/mooncrawl/stats_worker/dashboard.py, crawlers/mooncrawl/mooncrawl/stats_worker/queries.py
Improved metada-crawler with leak logic and check of distinct latest `tx_call` names `per token`.
Crawler will leak only tokens wich have tx_calls wich not transfers.
Manualy.
Run state-crawler.
```
python -m mooncrawl.state_crawler.cli --access-id "${NB_CONTROLLER_ACCESS_ID}" crawl-jobs --blockchain polygon --infura --jobs-file /home/ubuntu/moonstream/crawlers/mooncrawl/mooncrawl/state_crawler/jobs/polygon-jobs.json
```
Runs metadata crawl once.
```
python -m mooncrawl.metadata_crawler.cli crawl --blockchain polygon
```
Wait untill new not apear new tx_call wich not transfer and runs metadata crawl again.
=> Add leak of parsed data.

engineapi/engineapi/actions.py, engineapi/engineapi/api.py, engineapi/engineapi/auth.py, engineapi/engineapi/contracts/web3_util.py, engineapi/engineapi/data.py, engineapi/engineapi/middleware.py, engineapi/engineapi/rc.py, engineapi/engineapi/routes/admin.py, engineapi/engineapi/routes/configs.py, engineapi/engineapi/routes/dropper.py, engineapi/engineapi/routes/leaderboard.py, engineapi/engineapi/routes/metatx.py, engineapi/engineapi/routes/play.py, engineapi/engineapi/scripts/fill_raw_amount.py, engineapi/engineapi/settings.py, engineapi/engineapi/signatures.py, engineapi/engineapi/test_middleware.py, engineapi/sample.env, engineapi/setup.py
At application startup:
- Fetch CORS settings from application resources application-config
- Fetch CORS from env variable and asure all this origins represented in resource application-config
- Write it to Redis cache
With `/cors` endpoint each user can add more origins to CORS application-config, after it the cache and 'allowed_origins' will be extended. List of all allowed origins available only to Moonstream admin.
As a source used design doc: https://docs.google.com/document/d/1ZGXAvGTH1zj3jr4hUWN-0-9VHrHcAgcQBYvywqg3WpM/edit#heading=h.5gdp4oo0iu7i
Tested locally.
=> Modified CORS middleware with Redis cache workflow

nodebalancer/cmd/nodebalancer/blockchain.go
Specified default zksync methods for nodebalancer from https://era.zksync.io/docs/api/api.html
=> Nodebalancer zksync blockchain support

engineapi/engineapi/contracts_actions.py, engineapi/engineapi/data.py, engineapi/engineapi/routes/metatx.py
If query `verify=true` provided with POST /requests endpoint, it first verify call_requests not presented in database, if so, then return request_ids
=> Verify if requests exists before push new list

engineapi/engineapi/contracts_actions.py, engineapi/engineapi/data.py, engineapi/engineapi/middleware.py, engineapi/engineapi/models.py, engineapi/engineapi/routes/metatx.py, engineapi/engineapi/scripts/metatx_resources.py, engineapi/engineapi/settings.py, engineapi/requirements.txt, engineapi/setup.py
Each registered contract has one resource with attached ResourceHolderPermissions that describe the permissions of users or groups.
Design doc: https://docs.google.com/document/d/1FTP4208f1-h4Gp53nxYw0PBLEm4E9xl5jUa25jkXWso/edit
=> Metatx under resources control

crawlers/mooncrawl/mooncrawl/actions.py, crawlers/mooncrawl/mooncrawl/api.py, crawlers/mooncrawl/mooncrawl/data.py, crawlers/mooncrawl/mooncrawl/db.py, crawlers/mooncrawl/mooncrawl/leaderboards_generator/cli.py, crawlers/mooncrawl/mooncrawl/leaderboards_generator/utils.py, crawlers/mooncrawl/mooncrawl/settings.py, crawlers/mooncrawl/mooncrawl/stats_worker/queries.py, crawlers/mooncrawl/mooncrawl/version.py, crawlers/mooncrawl/sample.env, moonstreamapi/moonstreamapi/data.py, moonstreamapi/moonstreamapi/routes/queries.py
New query parameters which define database of query execution.
```
POST http://127.0.0.1:7481/queries/Leaderboard_swaps/update_data?customer_id=<db-id>&instance_id=1
Authorization: Bearer <moonstream-token>
Content-Type: application/json
{
"blockchain": "arbitrum_one",
"params": {
}
}
```
Update leaderboards generator to use new parameters in query execution flow.
Add env variables.
MOONSTREAM_DB_V3_CONTROLLER_API = 'https://mdb-v3-api.moonstream.to'
MOONSTREAM_DB_V3_SCHEMA_NAME = 'blockchain'
=> Add queryAPI v3 and update leaderboard generator.

.github/workflows/release.clients.python.yml, .github/workflows/release.mooncrawl.yml, .github/workflows/release.moonstreamapi.yml, .github/workflows/release.moonstreamdb.yml, .github/workflows/release.moonstreamdbv3.yml, .github/workflows/release.types.python.yml
Used `build` with support of [PEP 625](https://peps.python.org/pep-0625/).
Also used `MANIFEST.in` to include `version.txt` files in isolated build environment, detailed documation at: https://setuptools.pypa.io/en/latest/userguide/miscellaneous.html .
Packages with changes:
- PR https://github.com/moonstream-to/api/pull/1152
- PR https://github.com/moonstream-to/api/pull/1153
=> Release packages update

nodebalancer/README.md, nodebalancer/cmd/nodebalancer/balances.go, nodebalancer/cmd/nodebalancer/configs.go
This pull request includes several changes to the `nodebalancer`. The most important changes include updating the JSON structure in the README, modifying the `balances.go` and `configs.go` files to include additional chain information, and updating the `contracts.json` structure.
* [`nodebalancer/README.md`](diffhunk://#diff-18e1992c4e745a5dcdd6ae1d2602f9e557364926ecd714a6cdbd03ba2fe9bc74L146-R176): Updated the JSON structure to include additional chain information such as `chain_id`, `name`, and `image_url`. The top-level keys are now chain IDs, and the `balances` are nested within each chain object. [[1]](diffhunk://#diff-18e1992c4e745a5dcdd6ae1d2602f9e557364926ecd714a6cdbd03ba2fe9bc74L146-R176) [[2]](diffhunk://#diff-18e1992c4e745a5dcdd6ae1d2602f9e557364926ecd714a6cdbd03ba2fe9bc74L175-R …
=> New balances structure.
